import { StyleSheet } from 'react-native';
import { COLORS } from '@/constants/colors';

export const analiticaStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: COLORS.primary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: COLORS.primary,
  },
  backBtn: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.white,
  },
  bellBtn: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 24,
  },
  body: {
    flex: 1,
    backgroundColor: COLORS.bg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
  },
  bodyContent: {
    padding: 20,
    gap: 14,
    paddingBottom: 40,
  },
  searchRow: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: 14,
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 6,
    paddingVertical: 6,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: COLORS.text,
    paddingVertical: 8,
  },
  searchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    height: 38,
    borderRadius: 10,
    backgroundColor: COLORS.text,
    justifyContent: 'center',
  },
  searchBtnText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '700',
  },
  anioBadgeWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  anioBadge: {
    backgroundColor: COLORS.white,
    borderRadius: 50,
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  anioBadgeText: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.text,
  },
  mesNav: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  mesNavBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  mesNavBtnDisabled: {
    opacity: 0.35,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 22,
    padding: 20,
    gap: 20,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  clienteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: COLORS.white,
    fontWeight: '800',
    fontSize: 15,
  },
  clienteNombre: {
    fontSize: 17,
    fontWeight: '700',
    color: COLORS.text,
  },
  kpiRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  kpiItem: {
    flex: 1,
    gap: 4,
  },
  kpiDivider: {
    width: 1,
    height: 64,
    backgroundColor: COLORS.border,
    marginHorizontal: 14,
  },
  kpiIconSquareGreen: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#3EBF7A',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  kpiIconSquareRed: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#E53935',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  kpiIconSymbol: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '700',
  },
  kpiLabel: {
    fontSize: 12,
    color: COLORS.textMuted,
    fontWeight: '500',
  },
  kpiValueGreen: {
    fontSize: 17,
    fontWeight: '800',
    color: COLORS.text,
  },
  kpiValueRed: {
    fontSize: 17,
    fontWeight: '800',
    color: '#E53935',
  },
  chartCard: {
    backgroundColor: '#E8F8F0',
    borderRadius: 16,
    padding: 14,
    gap: 8,
  },
  chartHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  chartTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.text,
  },
  chartActions: {
    flexDirection: 'row',
    gap: 8,
  },
  chartActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    height: 44,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
  },
  chartActionBtnText: {
    color: COLORS.white,
    fontSize: 11,
    fontWeight: '700',
  },
  chartActionBtnDisabled: {
    opacity: 0.4,
  },
  chartLegend: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  legendText: {
    fontSize: 11,
    fontWeight: '500',
    color: COLORS.textMuted,
  },
  chartBody: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  chartYAxis: {
    width: 32,
    height: 150,
    position: 'relative',
  },
  chartYLabel: {
    position: 'absolute',
    right: 0,
    fontSize: 9,
    lineHeight: 12,
    color: '#7EB8D4',
    textAlign: 'right',
  },
  chartPlot: {
    flex: 1,
    height: 150,
    position: 'relative',
  },
  chartEmptyOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(232, 248, 240, 0.78)',
  },
  chartEmptyText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textMuted,
  },
  chartXAxis: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 38,
    marginTop: 4,
  },
  chartXLabel: {
    fontSize: 9,
    color: '#B0BEC5',
    flex: 1,
    textAlign: 'center',
  },
  distSection: {
    gap: 10,
  },
  distTitle: {
    fontSize: 13,
    fontStyle: 'italic',
    fontWeight: '600',
    color: COLORS.text,
  },
  distSubtitle: {
    fontSize: 11,
    color: COLORS.textMuted,
    marginTop: -4,
    marginBottom: 2,
  },
  distRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  distBadge: {
    minWidth: 44,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 50,
    alignItems: 'center',
  },
  distBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.white,
  },
  distTrack: {
    flex: 1,
    backgroundColor: '#EEF2F1',
    borderRadius: 50,
    paddingVertical: 8,
    paddingHorizontal: 12,
    overflow: 'hidden',
    position: 'relative',
  },
  distFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
  },
  distLabel: {
    fontSize: 12,
    color: COLORS.textMuted,
    zIndex: 1,
  },
  emptyState: {
    alignItems: 'center',
    marginTop: 60,
  },
  emptyText: {
    fontSize: 14,
    color: COLORS.textMuted,
    textAlign: 'center',
  },
  loader: {
    marginTop: 40,
  },
});
